import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import DataBaseConnection.Connector;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
/**
 *
 * @author domin
 */
public class AddResults extends javax.swing.JDialog {

    /**
     * Creates new form AddResults
     */
    public AddResults(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        populatestud();
        populatesub();
    }

    AddResults() {
            initComponents();
        populatestud();
        populatesub();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        studentComboBox = new Custom_Components.ComboBox();
        assessmentComboBox = new Custom_Components.ComboBox();
        scoreField = new Custom_Components.RoundTextField();
        roundedButton1 = new Custom_Components.RoundedButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        dateField = new Custom_Components.RoundTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ASSESSMENT RESULT");

        studentComboBox.setLabeText("Select Student");

        assessmentComboBox.setLabeText("Select Subject");
        assessmentComboBox.setName(""); // NOI18N
        assessmentComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assessmentComboBoxActionPerformed(evt);
            }
        });

        scoreField.setPlaceholderText("Enter Score");

        roundedButton1.setBackground(new java.awt.Color(0, 255, 0));
        roundedButton1.setText("Confirm");
        roundedButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundedButton1ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image Folder/exit-full-screen.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image Folder/left-arrow.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        dateField.setPlaceholderText("Enter Date");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(studentComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(assessmentComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scoreField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(roundedButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(studentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(assessmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(scoreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roundedButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void assessmentComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assessmentComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_assessmentComboBoxActionPerformed

    private void roundedButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundedButton1ActionPerformed

    String studentName = studentComboBox.getSelectedItem().toString().trim();
    String assessmentTitle = assessmentComboBox.getSelectedItem().toString().trim();
    String scoreText = scoreField.getText().trim();
    String dateText = dateField.getText().trim();

    if (studentName.isEmpty() || assessmentTitle.isEmpty() || scoreText.isEmpty() || dateText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "All fields are required.");
        return;
    }

    int score;
    try {
        score = Integer.parseInt(scoreText);
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Score must be a number.");
        return;
    }

    java.sql.Date sqlDate;
    try {
        java.util.Date parsedDate = new SimpleDateFormat("yyyy-MM-dd").parse(dateText);
        sqlDate = new java.sql.Date(parsedDate.getTime());
    } catch (ParseException ex) {
        JOptionPane.showMessageDialog(this, "Invalid date format. Use yyyy-MM-dd.");
        return;
    }

    try (Connection con = Connector.getConnection()) {
        // Lookup StudentID
        String studentSQL = "SELECT StudentID FROM student WHERE CONCAT(LastName, ', ', FirstName) = ?";
        PreparedStatement studentPst = con.prepareStatement(studentSQL);
        studentPst.setString(1, studentName);
        ResultSet studentRs = studentPst.executeQuery();

        // Lookup AssessmentID
        String assessSQL = "SELECT AssessmentID FROM assessment WHERE Title = ?";
        PreparedStatement assessPst = con.prepareStatement(assessSQL);
        assessPst.setString(1, assessmentTitle);
        ResultSet assessRs = assessPst.executeQuery();

        if (studentRs.next() && assessRs.next()) {
            int studentID = studentRs.getInt("StudentID");
            int assessmentID = assessRs.getInt("AssessmentID");

            String insertSQL = "INSERT INTO assessmentresult (StudentID, AssessmentID, Score, DateTaken) VALUES (?, ?, ?, ?)";
            PreparedStatement pst = con.prepareStatement(insertSQL);
            pst.setInt(1, studentID);
            pst.setInt(2, assessmentID);
            pst.setInt(3, score);
            pst.setDate(4, sqlDate);
            pst.executeUpdate();

            String rating = getRating(score);
            JOptionPane.showMessageDialog(this, "Result saved! Rating: " + rating);
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Student or Assessment not found.");
        }

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        ex.printStackTrace();
    }
    }//GEN-LAST:event_roundedButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        AddOptions add = new AddOptions();
add.setVisible(rootPaneCheckingEnabled);
add.setLocationRelativeTo(null);
this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void populatestud(){
        try (Connection con = Connector.getConnection()) {
    String sql = "SELECT CONCAT(LastName, ', ', FirstName) AS FullName FROM student";
    PreparedStatement pst = con.prepareStatement(sql);
    ResultSet rs = pst.executeQuery();
    while (rs.next()) {
        studentComboBox.addItem(rs.getString("FullName"));
    }
}catch (SQLException ex) {
    JOptionPane.showMessageDialog(this, "Error loading subjects: " + ex.getMessage());
    ex.printStackTrace();
    }
    }
    private void populatesub(){
        try (Connection con = Connector.getConnection()) {
    String sql = "SELECT Title FROM assessment";
    PreparedStatement pst = con.prepareStatement(sql);
    ResultSet rs = pst.executeQuery();
    while (rs.next()) {
        assessmentComboBox.addItem(rs.getString("Title"));
    }
}catch (SQLException ex) {
    JOptionPane.showMessageDialog(this, "Error loading students: " + ex.getMessage());
    ex.printStackTrace();
    }
    }
    private String getRating(int score) {
    if (score == 100) return "God Mode";
    else if (score >= 85) return "Outstanding";
    else if (score >= 70) return "Good";
    else if (score >= 50) return "Fair";
    else return "Needs Improvement";
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddResults dialog = new AddResults(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Custom_Components.ComboBox assessmentComboBox;
    private Custom_Components.RoundTextField dateField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private Custom_Components.RoundedButton roundedButton1;
    private Custom_Components.RoundTextField scoreField;
    private Custom_Components.ComboBox studentComboBox;
    // End of variables declaration//GEN-END:variables
}
