/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author bello
 */
import Custom_Components.RoundedPanel;
import Custom_Components.RoundedButton;
import Custom_Components.RoundPasswordField;
import Custom_Components.RoundTextField;
import Custom_Components.ImageButton;
import Custom_Components.ProfilePanel;
import Custom_Components.ShowHideButton;
import Custom_Components.TextPrompt;
import Custom_Components.ThinScrollBarUI;
import Custom_Components.ThinScrollDemo;
import DataBaseConnection.Connector;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.RenderingHints;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;
public class AddStudMainDialog extends javax.swing.JDialog {

    /**
     * Creates new form AddStudMainDialog
     */
    public AddStudMainDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    AddStudMainDialog() {
                this((java.awt.Frame) null, true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddMainPanel = new RoundedPanel(0);
        TitleLabel = new javax.swing.JLabel();
        PersonalDetialsLabel = new javax.swing.JLabel();
        LastnameTextField = new Custom_Components.RoundTextField();
        FirstnameTextField = new Custom_Components.RoundTextField();
        MiddlenameTextField = new Custom_Components.RoundTextField();
        WhereDoYouLiveLabel = new javax.swing.JLabel();
        BarangayTextField = new Custom_Components.RoundTextField();
        CityTextField = new Custom_Components.RoundTextField();
        ProvinceTextField = new Custom_Components.RoundTextField();
        CountryTextField = new Custom_Components.RoundTextField();
        ContactLabel = new javax.swing.JLabel();
        ContactNumberTextField = new Custom_Components.RoundTextField();
        UsernameTextField = new Custom_Components.RoundTextField();
        PasswordTextField = new Custom_Components.RoundPasswordField();
        showHideButton1 = new ShowHideButton();
        ConfirmPasswordTextField = new Custom_Components.RoundPasswordField();
        showHideButton2 = new ShowHideButton();
        CreateProfilePicture = new javax.swing.JLabel();
        profilePathField = new Custom_Components.RoundTextField();
        PhotoUploader = new Custom_Components.RoundedButton();
        profilePicLabel = new Custom_Components.ProfilePanel();
        AddStudButton = new RoundedButton();
        ProgramTextField1 = new Custom_Components.RoundTextField();
        YearTextField1 = new Custom_Components.RoundTextField();
        SectionTextField1 = new Custom_Components.RoundTextField();
        roundedButton2 = new Custom_Components.RoundedButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        AddMainPanel.setBackground(new java.awt.Color(255, 255, 255));
        AddMainPanel.setPreferredSize(new java.awt.Dimension(761, 693));

        TitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        TitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleLabel.setText("Add Student");
        TitleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        PersonalDetialsLabel.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        PersonalDetialsLabel.setText("PERSONAL DETAILS");

        LastnameTextField.setPlaceholderText("Last name");
        LastnameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastnameTextFieldActionPerformed(evt);
            }
        });

        FirstnameTextField.setPlaceholderText("First name");
        FirstnameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstnameTextFieldActionPerformed(evt);
            }
        });

        MiddlenameTextField.setPlaceholderText("Middle name");
        MiddlenameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiddlenameTextFieldActionPerformed(evt);
            }
        });

        WhereDoYouLiveLabel.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        WhereDoYouLiveLabel.setText("WHERE DO YOU LIVE");

        BarangayTextField.setPlaceholderText("Barangay");
        BarangayTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarangayTextFieldActionPerformed(evt);
            }
        });

        CityTextField.setPlaceholderText("City");
        CityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CityTextFieldActionPerformed(evt);
            }
        });

        ProvinceTextField.setPlaceholderText("Province");
        ProvinceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProvinceTextFieldActionPerformed(evt);
            }
        });

        CountryTextField.setPlaceholderText("Country");
        CountryTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CountryTextFieldActionPerformed(evt);
            }
        });

        ContactLabel.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        ContactLabel.setText("CONTACT");

        ContactNumberTextField.setPlaceholderText("Contact Number");
        ContactNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactNumberTextFieldActionPerformed(evt);
            }
        });

        UsernameTextField.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image Folder/user.png"))); // NOI18N
        UsernameTextField.setPlaceholderText("Username");
        UsernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameTextFieldActionPerformed(evt);
            }
        });

        PasswordTextField.setPlaceholderText("Password");

        showHideButton1.setText("showHideButton1");
        showHideButton1.setHideIcon(new javax.swing.ImageIcon(getClass().getResource("/Image Folder/eye.png"))); // NOI18N
        showHideButton1.setShowIcon(new javax.swing.ImageIcon(getClass().getResource("/Image Folder/hidden.png"))); // NOI18N
        showHideButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showHideButton1ActionPerformed(evt);
            }
        });

        ConfirmPasswordTextField.setPlaceholderText("Confirm Password");

        showHideButton2.setText("showHideButton1");
        showHideButton2.setHideIcon(new javax.swing.ImageIcon(getClass().getResource("/Image Folder/eye.png"))); // NOI18N
        showHideButton2.setShowIcon(new javax.swing.ImageIcon(getClass().getResource("/Image Folder/hidden.png"))); // NOI18N
        showHideButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showHideButton2ActionPerformed(evt);
            }
        });

        CreateProfilePicture.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        CreateProfilePicture.setText("CREATE PROFILE PICTURE");

        profilePathField.setMaximumSize(new java.awt.Dimension(64, 26));
        profilePathField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilePathFieldActionPerformed(evt);
            }
        });

        PhotoUploader.setText("Upload Photo");
        PhotoUploader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhotoUploaderActionPerformed(evt);
            }
        });

        profilePicLabel.setForeground(new java.awt.Color(153, 153, 153));
        profilePicLabel.setText("*Your Uploaded Profile Picture*");
        profilePicLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        AddStudButton.setBackground(new java.awt.Color(72, 130, 237));
        AddStudButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AddStudButton.setForeground(new java.awt.Color(255, 255, 255));
        AddStudButton.setText("Add Student");
        AddStudButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddStudButtonActionPerformed(evt);
            }
        });

        ProgramTextField1.setPlaceholderText("Program\n");
        ProgramTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProgramTextField1ActionPerformed(evt);
            }
        });

        YearTextField1.setPlaceholderText("Year");
        YearTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YearTextField1ActionPerformed(evt);
            }
        });

        SectionTextField1.setPlaceholderText("Section\n");
        SectionTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SectionTextField1ActionPerformed(evt);
            }
        });

        roundedButton2.setBackground(new java.awt.Color(72, 130, 237));
        roundedButton2.setForeground(new java.awt.Color(255, 255, 255));
        roundedButton2.setText("Back");
        roundedButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        roundedButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundedButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddMainPanelLayout = new javax.swing.GroupLayout(AddMainPanel);
        AddMainPanel.setLayout(AddMainPanelLayout);
        AddMainPanelLayout.setHorizontalGroup(
            AddMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddMainPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(AddMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddMainPanelLayout.createSequentialGroup()
                        .addGroup(AddMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(UsernameTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AddMainPanelLayout.createSequentialGroup()
                                .addGroup(AddMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(ConfirmPasswordTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(PasswordTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(AddMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(showHideButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(showHideButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(AddMainPanelLayout.createSequentialGroup()
                        .addGroup(AddMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AddMainPanelLayout.createSequentialGroup()
                                .addComponent(ProgramTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(YearTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SectionTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(PersonalDetialsLabel)
                            .addGroup(AddMainPanelLayout.createSequentialGroup()
                                .addComponent(LastnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FirstnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MiddlenameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AddMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(ContactNumberTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(WhereDoYouLiveLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ContactLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AddMainPanelLayout.createSequentialGroup()
                                    .addComponent(BarangayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(CityTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ProvinceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(CountryTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(AddMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddMainPanelLayout.createSequentialGroup()
                                .addComponent(profilePicLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddMainPanelLayout.createSequentialGroup()
                                .addGroup(AddMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CreateProfilePicture)
                                    .addComponent(profilePathField, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddMainPanelLayout.createSequentialGroup()
                                .addComponent(PhotoUploader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(131, 131, 131))))))
            .addGroup(AddMainPanelLayout.createSequentialGroup()
                .addGroup(AddMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddMainPanelLayout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(TitleLabel))
                    .addGroup(AddMainPanelLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(roundedButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(AddStudButton, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        AddMainPanelLayout.setVerticalGroup(
            AddMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddMainPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(TitleLabel)
                .addGap(18, 18, 18)
                .addGroup(AddMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddMainPanelLayout.createSequentialGroup()
                        .addComponent(PersonalDetialsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AddMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LastnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FirstnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MiddlenameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AddMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ProgramTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(YearTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SectionTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addComponent(WhereDoYouLiveLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AddMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BarangayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProvinceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(CountryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(ContactLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ContactNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AddMainPanelLayout.createSequentialGroup()
                        .addComponent(CreateProfilePicture)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(profilePathField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PhotoUploader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(profilePicLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, Short.MAX_VALUE)
                .addComponent(UsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showHideButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showHideButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(AddMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(roundedButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddStudButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AddMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AddMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(777, 707));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LastnameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastnameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastnameTextFieldActionPerformed

    private void FirstnameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstnameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstnameTextFieldActionPerformed

    private void MiddlenameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiddlenameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MiddlenameTextFieldActionPerformed

    private void BarangayTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarangayTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BarangayTextFieldActionPerformed

    private void CityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CityTextFieldActionPerformed

    private void ProvinceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProvinceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProvinceTextFieldActionPerformed

    private void CountryTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CountryTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CountryTextFieldActionPerformed

    private void ContactNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactNumberTextFieldActionPerformed

    private void UsernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameTextFieldActionPerformed

    private void showHideButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showHideButton1ActionPerformed
        // TODO add your handling code here:
        if (showHideButton1.isPasswordVisible()) {
            // If it's visible, show the password text
            PasswordTextField.setEchoChar((char) 0);
        } else {
            // If it's not visible, hide the password text
            PasswordTextField.setEchoChar('*');
        }
    }//GEN-LAST:event_showHideButton1ActionPerformed

    private void showHideButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showHideButton2ActionPerformed
        // TODO add your handling code here:
        if (showHideButton2.isPasswordVisible()) {
            // If it's visible, show the password text
            ConfirmPasswordTextField.setEchoChar((char) 0);
        } else {
            // If it's not visible, hide the password text
            ConfirmPasswordTextField.setEchoChar('*');
        }
    }//GEN-LAST:event_showHideButton2ActionPerformed

    private void PhotoUploaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhotoUploaderActionPerformed
JFileChooser fileChooser = new JFileChooser();
fileChooser.setDialogTitle("Select Profile Picture");
fileChooser.setFileFilter(new FileNameExtensionFilter(
        "Image files", "jpg", "jpeg", "png", "gif"));

int result = fileChooser.showOpenDialog(null);
if (result == JFileChooser.APPROVE_OPTION) {
    File selectedFile = fileChooser.getSelectedFile();
    selectedProfilePath = selectedFile.getAbsolutePath(); // use the class-level variable
    profilePathField.setText(selectedProfilePath); // optional

    // Load and display the image
    ImageIcon icon = new ImageIcon(selectedProfilePath);
    Image img = icon.getImage().getScaledInstance(
            profilePicLabel.getWidth(),
            profilePicLabel.getHeight(),
            Image.SCALE_SMOOTH
    );
    profilePicLabel.setIcon(new ImageIcon(img));
}
    }//GEN-LAST:event_PhotoUploaderActionPerformed

    private void profilePathFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilePathFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profilePathFieldActionPerformed

    private void AddStudButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddStudButtonActionPerformed
        try (Connection con = Connector.getConnection()) {
    // 1️⃣ Gather input
    String lastName = LastnameTextField.getText().trim();
    String firstName = FirstnameTextField.getText().trim();
    String middleName = MiddlenameTextField.getText().trim();
    String program = ProgramTextField1.getText().trim();
    String yearLevel = YearTextField1.getText().trim();
    String section = SectionTextField1.getText().trim();
    String barangay = BarangayTextField.getText().trim();
    String city = CityTextField.getText().trim();
    String province = ProvinceTextField.getText().trim();
    String country = CountryTextField.getText().trim();
    String contactNumber = ContactNumberTextField.getText().trim();
    String username = UsernameTextField.getText().trim();
    String password = new String(PasswordTextField.getPassword()).trim();
    String confirmPassword = new String(ConfirmPasswordTextField.getPassword()).trim();

    // 2️⃣ Validate input
    if (lastName.isEmpty() || firstName.isEmpty() || middleName.isEmpty() || program.isEmpty() ||
        yearLevel.isEmpty() || section.isEmpty() || barangay.isEmpty() || city.isEmpty() ||
        province.isEmpty() || country.isEmpty() || contactNumber.isEmpty() ||
        username.isEmpty() || password.isEmpty() || confirmPassword.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill out all required fields.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (!password.equals(confirmPassword)) {
        JOptionPane.showMessageDialog(this, "Passwords do not match.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // 3️⃣ Check for existing username
    String checkSQL = "SELECT COUNT(*) FROM student WHERE Username = ?";
    PreparedStatement checkPst = con.prepareStatement(checkSQL);
    checkPst.setString(1, username);
    ResultSet checkRs = checkPst.executeQuery();
    if (checkRs.next() && checkRs.getInt(1) > 0) {
        JOptionPane.showMessageDialog(this, "Username already exists.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // 4️⃣ Handle profile photo
    String profilePicDestPath = null;
    if (selectedProfilePath != null) {
        try {
            File source = new File(selectedProfilePath);
            String destDir = "profile_pics/";
            new File(destDir).mkdirs(); // create folder if not exists
            profilePicDestPath = destDir + "student_" + username + ".jpg";
            Files.copy(source.toPath(), new File(profilePicDestPath).toPath(), StandardCopyOption.REPLACE_EXISTING);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error saving profile picture: " + ex.getMessage());
        }
    }

    // 5️⃣ Insert student
    String insertSQL = "INSERT INTO student (LastName, FirstName, MiddleName, Program, YearLevel, Section, " +
                       "Barangay, City, Province, Country, Contact_number, Username, Password) " +
                       "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
    PreparedStatement pst = con.prepareStatement(insertSQL, Statement.RETURN_GENERATED_KEYS);
    pst.setString(1, lastName);
    pst.setString(2, firstName);
    pst.setString(3, middleName);
    pst.setString(4, program);
    pst.setString(5, yearLevel);
    pst.setString(6, section);
    pst.setString(7, barangay);
    pst.setString(8, city);
    pst.setString(9, province);
    pst.setString(10, country);
    pst.setString(11, contactNumber);
    pst.setString(12, username);
    pst.setString(13, password);
    pst.executeUpdate();

    // 6️⃣ Get generated StudentID
    ResultSet rs = pst.getGeneratedKeys();
    int studentID = -1;
    if (rs.next()) {
        studentID = rs.getInt(1);
    }

    // 7️⃣ Insert photo into student_photos
    if (profilePicDestPath != null && studentID != -1) {
        String photoSQL = "INSERT INTO student_photos (StudentID, PhotoPath, Description) VALUES (?, ?, ?)";
        PreparedStatement photoPst = con.prepareStatement(photoSQL);
        photoPst.setInt(1, studentID);
        photoPst.setString(2, profilePicDestPath);
        photoPst.setString(3, "Profile photo");
        photoPst.executeUpdate();
    }

    // 8️⃣ Success message
    JOptionPane.showMessageDialog(this,
        "Registration successful!\nYour User ID is: " + studentID,
        "Success", JOptionPane.INFORMATION_MESSAGE);

    this.dispose(); // close registration form

} catch (SQLException ex) {
    JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage(), "SQL Error", JOptionPane.ERROR_MESSAGE);
    ex.printStackTrace();
} catch (HeadlessException ex) {
    JOptionPane.showMessageDialog(this, "Unexpected error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    ex.printStackTrace();
}
    }//GEN-LAST:event_AddStudButtonActionPerformed

    private void ProgramTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProgramTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProgramTextField1ActionPerformed

    private void YearTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YearTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YearTextField1ActionPerformed

    private void SectionTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SectionTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SectionTextField1ActionPerformed

    private void roundedButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundedButton2ActionPerformed
        // TODO add your handling code here:
        
        AddOptions add = new AddOptions();
        this.dispose();   
        add.setVisible(true);            // then show it
            
    }//GEN-LAST:event_roundedButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStudMainDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStudMainDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStudMainDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStudMainDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddStudMainDialog dialog = new AddStudMainDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
private String selectedProfilePath;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddMainPanel;
    private javax.swing.JButton AddStudButton;
    private Custom_Components.RoundTextField BarangayTextField;
    private Custom_Components.RoundTextField CityTextField;
    private Custom_Components.RoundPasswordField ConfirmPasswordTextField;
    private javax.swing.JLabel ContactLabel;
    private Custom_Components.RoundTextField ContactNumberTextField;
    private Custom_Components.RoundTextField CountryTextField;
    private javax.swing.JLabel CreateProfilePicture;
    private Custom_Components.RoundTextField FirstnameTextField;
    private Custom_Components.RoundTextField LastnameTextField;
    private Custom_Components.RoundTextField MiddlenameTextField;
    private Custom_Components.RoundPasswordField PasswordTextField;
    private javax.swing.JLabel PersonalDetialsLabel;
    private Custom_Components.RoundedButton PhotoUploader;
    private Custom_Components.RoundTextField ProgramTextField1;
    private Custom_Components.RoundTextField ProvinceTextField;
    private Custom_Components.RoundTextField SectionTextField1;
    private javax.swing.JLabel TitleLabel;
    private Custom_Components.RoundTextField UsernameTextField;
    private javax.swing.JLabel WhereDoYouLiveLabel;
    private Custom_Components.RoundTextField YearTextField1;
    private Custom_Components.RoundTextField profilePathField;
    private Custom_Components.ProfilePanel profilePicLabel;
    private Custom_Components.RoundedButton roundedButton2;
    private Custom_Components.ShowHideButton showHideButton1;
    private Custom_Components.ShowHideButton showHideButton2;
    // End of variables declaration//GEN-END:variables
}
