/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author bello
 */
import Custom_Components.RoundedPanel;
import Custom_Components.RoundedButton;
import Custom_Components.RoundPasswordField;
import Custom_Components.RoundTextField;
import Custom_Components.ImageButton;
import Custom_Components.ProfilePanel;
import Custom_Components.ShowHideButton;
import Custom_Components.TextPrompt;
import Custom_Components.ThinScrollBarUI;
import Custom_Components.ThinScrollDemo;
import DataBaseConnection.Connector;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.HeadlessException;
import java.awt.RenderingHints;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
public class AddStudMainDialog extends javax.swing.JDialog {

    /**
     * Creates new form AddStudMainDialog
     */
    public AddStudMainDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddMainPanel = new RoundedPanel(0);
        TitleLabel = new javax.swing.JLabel();
        PersonalDetialsLabel = new javax.swing.JLabel();
        LastnameTextField = new Custom_Components.RoundTextField();
        FirstnameTextField = new Custom_Components.RoundTextField();
        MiddlenameTextField = new Custom_Components.RoundTextField();
        WhereDoYouLiveLabel = new javax.swing.JLabel();
        BarangayTextField = new Custom_Components.RoundTextField();
        CityTextField = new Custom_Components.RoundTextField();
        ProvinceTextField = new Custom_Components.RoundTextField();
        CountryTextField = new Custom_Components.RoundTextField();
        ContactLabel = new javax.swing.JLabel();
        ContactNumberTextField = new Custom_Components.RoundTextField();
        UsernameTextField = new Custom_Components.RoundTextField();
        PasswordTextField = new Custom_Components.RoundPasswordField();
        showHideButton1 = new ShowHideButton();
        ConfirmPasswordTextField = new Custom_Components.RoundPasswordField();
        showHideButton2 = new ShowHideButton();
        CreateProfilePicture = new javax.swing.JLabel();
        profilePathField = new Custom_Components.RoundTextField();
        PhotoUploader = new Custom_Components.RoundedButton();
        profilePicLabel = new Custom_Components.ProfilePanel();
        AddStudButton = new RoundedButton();
        BackButton = new ImageButton();
        CloseButton = new ImageButton();
        ProgramTextField1 = new Custom_Components.RoundTextField();
        YearTextField1 = new Custom_Components.RoundTextField();
        SectionTextField1 = new Custom_Components.RoundTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        AddMainPanel.setBackground(new java.awt.Color(255, 255, 255));

        TitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        TitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleLabel.setText("Add Student");
        TitleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        PersonalDetialsLabel.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        PersonalDetialsLabel.setText("PERSONAL DETAILS");

        LastnameTextField.setPlaceholderText("Last name");
        LastnameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastnameTextFieldActionPerformed(evt);
            }
        });

        FirstnameTextField.setPlaceholderText("First name");
        FirstnameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstnameTextFieldActionPerformed(evt);
            }
        });

        MiddlenameTextField.setPlaceholderText("Middle name");
        MiddlenameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiddlenameTextFieldActionPerformed(evt);
            }
        });

        WhereDoYouLiveLabel.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        WhereDoYouLiveLabel.setText("WHERE DO YOU LIVE");

        BarangayTextField.setPlaceholderText("Barangay");
        BarangayTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarangayTextFieldActionPerformed(evt);
            }
        });

        CityTextField.setPlaceholderText("City");
        CityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CityTextFieldActionPerformed(evt);
            }
        });

        ProvinceTextField.setPlaceholderText("Province");
        ProvinceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProvinceTextFieldActionPerformed(evt);
            }
        });

        CountryTextField.setPlaceholderText("Country");
        CountryTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CountryTextFieldActionPerformed(evt);
            }
        });

        ContactLabel.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        ContactLabel.setText("CONTACT");

        ContactNumberTextField.setPlaceholderText("Contact Number");
        ContactNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactNumberTextFieldActionPerformed(evt);
            }
        });

        UsernameTextField.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image Folder/user.png"))); // NOI18N
        UsernameTextField.setPlaceholderText("Username");
        UsernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameTextFieldActionPerformed(evt);
            }
        });

        PasswordTextField.setPlaceholderText("Password");

        showHideButton1.setText("showHideButton1");
        showHideButton1.setHideIcon(new javax.swing.ImageIcon(getClass().getResource("/Image Folder/eye.png"))); // NOI18N
        showHideButton1.setShowIcon(new javax.swing.ImageIcon(getClass().getResource("/Image Folder/hidden.png"))); // NOI18N
        showHideButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showHideButton1ActionPerformed(evt);
            }
        });

        ConfirmPasswordTextField.setPlaceholderText("Confirm Password");

        showHideButton2.setText("showHideButton1");
        showHideButton2.setHideIcon(new javax.swing.ImageIcon(getClass().getResource("/Image Folder/eye.png"))); // NOI18N
        showHideButton2.setShowIcon(new javax.swing.ImageIcon(getClass().getResource("/Image Folder/hidden.png"))); // NOI18N
        showHideButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showHideButton2ActionPerformed(evt);
            }
        });

        CreateProfilePicture.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        CreateProfilePicture.setText("CREATE PROFILE PICTURE");

        profilePathField.setMaximumSize(new java.awt.Dimension(64, 26));
        profilePathField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilePathFieldActionPerformed(evt);
            }
        });

        PhotoUploader.setText("Upload Photo");
        PhotoUploader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhotoUploaderActionPerformed(evt);
            }
        });

        profilePicLabel.setForeground(new java.awt.Color(153, 153, 153));
        profilePicLabel.setText("*Your Uploaded Profile Picture*");
        profilePicLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        AddStudButton.setBackground(new java.awt.Color(51, 153, 255));
        AddStudButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        AddStudButton.setForeground(new java.awt.Color(255, 255, 255));
        AddStudButton.setText("Add Student");
        AddStudButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddStudButtonActionPerformed(evt);
            }
        });

        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image Folder/left-arrow.png"))); // NOI18N
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        CloseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image Folder/exit-full-screen.png"))); // NOI18N
        CloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseButtonActionPerformed(evt);
            }
        });

        ProgramTextField1.setPlaceholderText("Program\n");
        ProgramTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProgramTextField1ActionPerformed(evt);
            }
        });

        YearTextField1.setPlaceholderText("Year");
        YearTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YearTextField1ActionPerformed(evt);
            }
        });

        SectionTextField1.setPlaceholderText("Section\n");
        SectionTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SectionTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddMainPanelLayout = new javax.swing.GroupLayout(AddMainPanel);
        AddMainPanel.setLayout(AddMainPanelLayout);
        AddMainPanelLayout.setHorizontalGroup(
            AddMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddMainPanelLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(TitleLabel)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(AddMainPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(AddMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddMainPanelLayout.createSequentialGroup()
                        .addComponent(ProgramTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(YearTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SectionTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(AddMainPanelLayout.createSequentialGroup()
                        .addGroup(AddMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PersonalDetialsLabel)
                            .addGroup(AddMainPanelLayout.createSequentialGroup()
                                .addComponent(LastnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FirstnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MiddlenameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AddMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(AddMainPanelLayout.createSequentialGroup()
                                        .addComponent(BarangayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CityTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ProvinceTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(ContactNumberTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CountryTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(UsernameTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(profilePathField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(AddStudButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(AddMainPanelLayout.createSequentialGroup()
                                        .addGroup(AddMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(WhereDoYouLiveLabel)
                                            .addComponent(ContactLabel)
                                            .addGroup(AddMainPanelLayout.createSequentialGroup()
                                                .addGroup(AddMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(ConfirmPasswordTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(PasswordTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(AddMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(showHideButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(showHideButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(CreateProfilePicture))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(AddMainPanelLayout.createSequentialGroup()
                                        .addComponent(BackButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(CloseButton)))
                                .addGroup(AddMainPanelLayout.createSequentialGroup()
                                    .addGroup(AddMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(AddMainPanelLayout.createSequentialGroup()
                                            .addGap(122, 122, 122)
                                            .addComponent(PhotoUploader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(AddMainPanelLayout.createSequentialGroup()
                                            .addGap(69, 69, 69)
                                            .addComponent(profilePicLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(36, 36, 36))))
        );
        AddMainPanelLayout.setVerticalGroup(
            AddMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddMainPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(TitleLabel)
                .addGap(25, 25, 25)
                .addComponent(PersonalDetialsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LastnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FirstnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MiddlenameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProgramTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(YearTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SectionTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(WhereDoYouLiveLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BarangayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProvinceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(CountryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(ContactLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ContactNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(UsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showHideButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showHideButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(CreateProfilePicture)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(profilePathField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PhotoUploader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(profilePicLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(AddStudButton)
                .addGap(30, 30, 30)
                .addGroup(AddMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BackButton)
                    .addComponent(CloseButton))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AddMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AddMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(414, 977));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LastnameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastnameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastnameTextFieldActionPerformed

    private void FirstnameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstnameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstnameTextFieldActionPerformed

    private void MiddlenameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiddlenameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MiddlenameTextFieldActionPerformed

    private void BarangayTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarangayTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BarangayTextFieldActionPerformed

    private void CityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CityTextFieldActionPerformed

    private void ProvinceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProvinceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProvinceTextFieldActionPerformed

    private void CountryTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CountryTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CountryTextFieldActionPerformed

    private void ContactNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactNumberTextFieldActionPerformed

    private void UsernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameTextFieldActionPerformed

    private void showHideButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showHideButton1ActionPerformed
        // TODO add your handling code here:
        if (showHideButton1.isPasswordVisible()) {
            // If it's visible, show the password text
            PasswordTextField.setEchoChar((char) 0);
        } else {
            // If it's not visible, hide the password text
            PasswordTextField.setEchoChar('*');
        }
    }//GEN-LAST:event_showHideButton1ActionPerformed

    private void showHideButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showHideButton2ActionPerformed
        // TODO add your handling code here:
        if (showHideButton2.isPasswordVisible()) {
            // If it's visible, show the password text
            ConfirmPasswordTextField.setEchoChar((char) 0);
        } else {
            // If it's not visible, hide the password text
            ConfirmPasswordTextField.setEchoChar('*');
        }
    }//GEN-LAST:event_showHideButton2ActionPerformed

    private void PhotoUploaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhotoUploaderActionPerformed

    }//GEN-LAST:event_PhotoUploaderActionPerformed

    private void profilePathFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilePathFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profilePathFieldActionPerformed

    private void AddStudButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddStudButtonActionPerformed
        try(Connection con = Connector.getConnection()){
            String Lastname = LastnameTextField.getText();
            String Firstname = FirstnameTextField.getText();
            String Middlename = MiddlenameTextField.getText();
            String Program = ProgramTextField1.getText();
            String YearLevel = YearTextField1.getText();
            String Section = SectionTextField1.getText();
            String Barangay = BarangayTextField.getText();
            String City = CityTextField.getText();
            String Province = ProvinceTextField.getText();
            String Country = CountryTextField.getText();
            String CPnumber = ContactNumberTextField.getText();
            String Username = UsernameTextField.getText();
            String ProfilePhoto = profilePathField.getText();

            String Password = new String (PasswordTextField.getPassword());
            String ConfirmPassword = new String (ConfirmPasswordTextField.getPassword());

            if (Lastname.isEmpty()||Firstname.isEmpty() || Middlename.isEmpty()|| Program.isEmpty() || YearLevel.isEmpty()|| 
                    Section.isEmpty() || Barangay.isEmpty()|| City.isEmpty()
                    ||Province.isEmpty()||Country.isEmpty()||CPnumber.isEmpty() ||Username.isEmpty()||
                    Password.isEmpty()||ConfirmPassword.isEmpty()){
                JOptionPane.showMessageDialog(this, "Please make sure to fill out all requirements", "Error",JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (!Password.equals(ConfirmPassword)){
                JOptionPane.showMessageDialog(this, "Passwords Do not Match", "Error", JOptionPane.ERROR_MESSAGE);
            return;
            }
            //checks whether a username alreasy exist or not
            String CheckSql = "SELECT COUNT(*) FROM student WHERE Username = ?";
            PreparedStatement checkPst = con.prepareStatement(CheckSql);
            checkPst.setString(1,Username);
            ResultSet checkRs = checkPst.executeQuery();
        if (checkRs.next() && checkRs.getInt(1)>0){
            JOptionPane.showMessageDialog(this, "Username already exist", "Error", JOptionPane.ERROR_MESSAGE);
        return;
        }    

            String SQL = "INSERT INTO student"
                + "(`LastName`,`FirstName`,`MiddleName`,`Program`,`YearLevel`,`Section`,"
                + "`Barangay`,`City`,`Province`,`Country`,`Contact_number`,"
                + "`Username`,`Password`,`ProfilePhoto`)"
                + "VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

            PreparedStatement pst = con.prepareStatement(SQL,Statement.RETURN_GENERATED_KEYS);
            pst.setString(1, Lastname);
            pst.setString(2, Firstname);
            pst.setString(3, Middlename);
            pst.setString(4, Program);
            pst.setString(5, YearLevel);
            pst.setString(6, Section);
            pst.setString(7, Barangay);
            pst.setString(8, City);
            pst.setString(9, Province);
            pst.setString(10, Country);
            pst.setString(11, CPnumber);
            pst.setString(12, Username);
            pst.setString(13, Password);
            pst.setString(14, ProfilePhoto);

            pst.executeUpdate();

                // 6️⃣ Get generated student ID
            ResultSet rs = pst.getGeneratedKeys();
            int generatedId = -1;
            if (rs.next()) {
                generatedId = rs.getInt(1);
            }

            // 7️⃣ Success message
            JOptionPane.showMessageDialog(this,
                "Registration successful!\nYour User ID is: " + generatedId,
                "Success", JOptionPane.INFORMATION_MESSAGE);

            // Close sign-up form and open main form
            this.dispose();

        }catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage(),
                                          "SQL Error", JOptionPane.ERROR_MESSAGE);
        } catch (HeadlessException ex) {
            JOptionPane.showMessageDialog(this, "Unexpected error: " + ex.getMessage(),
                                          "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_AddStudButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackButtonActionPerformed

    private void CloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_CloseButtonActionPerformed

    private void ProgramTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProgramTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProgramTextField1ActionPerformed

    private void YearTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YearTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YearTextField1ActionPerformed

    private void SectionTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SectionTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SectionTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStudMainDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStudMainDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStudMainDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStudMainDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddStudMainDialog dialog = new AddStudMainDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddMainPanel;
    private javax.swing.JButton AddStudButton;
    private javax.swing.JButton BackButton;
    private Custom_Components.RoundTextField BarangayTextField;
    private Custom_Components.RoundTextField CityTextField;
    private javax.swing.JButton CloseButton;
    private Custom_Components.RoundPasswordField ConfirmPasswordTextField;
    private javax.swing.JLabel ContactLabel;
    private Custom_Components.RoundTextField ContactNumberTextField;
    private Custom_Components.RoundTextField CountryTextField;
    private javax.swing.JLabel CreateProfilePicture;
    private Custom_Components.RoundTextField FirstnameTextField;
    private Custom_Components.RoundTextField LastnameTextField;
    private Custom_Components.RoundTextField MiddlenameTextField;
    private Custom_Components.RoundPasswordField PasswordTextField;
    private javax.swing.JLabel PersonalDetialsLabel;
    private Custom_Components.RoundedButton PhotoUploader;
    private Custom_Components.RoundTextField ProgramTextField1;
    private Custom_Components.RoundTextField ProvinceTextField;
    private Custom_Components.RoundTextField SectionTextField1;
    private javax.swing.JLabel TitleLabel;
    private Custom_Components.RoundTextField UsernameTextField;
    private javax.swing.JLabel WhereDoYouLiveLabel;
    private Custom_Components.RoundTextField YearTextField1;
    private Custom_Components.RoundTextField profilePathField;
    private Custom_Components.ProfilePanel profilePicLabel;
    private Custom_Components.ShowHideButton showHideButton1;
    private Custom_Components.ShowHideButton showHideButton2;
    // End of variables declaration//GEN-END:variables
}
