
import Custom_Components.RoundedPanel;
import Custom_Components.ShowHideButton;
import Custom_Components.RoundedButton;
import Custom_Components.RoundPasswordField;
import Custom_Components.RoundTextField;
import Custom_Components.ImageButton;
import Custom_Components.HyperlinkLabel;
import Custom_Components.TextPrompt;
import javax.swing.*;
import DataBaseConnection.Connector;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

//boi check mo ako si laurence ako ang nag type neto
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author bello
 */
public class LoginDialog extends javax.swing.JDialog {

    /**
     * Creates new form LoginDialog
     */

    public LoginDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
    }
    
    LoginDialog() {
        this((java.awt.Frame) null, true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginPanel = new RoundedPanel(35);
        LoginLabel = new javax.swing.JLabel();
        LoginButton = new RoundedButton();
        SignupLabel = new HyperlinkLabel();
        SignupLabel1 = new HyperlinkLabel();
        CloseButton = new ImageButton();
        showHideButton1 = new Custom_Components.ShowHideButton();
        UsernameTextField = new Custom_Components.RoundTextField();
        PasswordTextField = new Custom_Components.RoundPasswordField();
        FontaineBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginPanel.setBackground(new java.awt.Color(255, 255, 255));
        LoginPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        LoginLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        LoginLabel.setText("LOGIN");
        LoginLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        LoginButton.setBackground(new java.awt.Color(51, 153, 255));
        LoginButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(255, 255, 255));
        LoginButton.setText("LOGIN");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        SignupLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SignupLabel.setText("Dont have an account? Sign Up");
        SignupLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignupLabelMouseClicked(evt);
            }
        });

        SignupLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SignupLabel1.setText("Forgot Password?");
        SignupLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignupLabel1MouseClicked(evt);
            }
        });

        CloseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image Folder/exit-full-screen.png"))); // NOI18N
        CloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseButtonActionPerformed(evt);
            }
        });

        showHideButton1.setText("showHideButton1");
        showHideButton1.setHideIcon(new javax.swing.ImageIcon(getClass().getResource("/Image Folder/eye.png"))); // NOI18N
        showHideButton1.setShowIcon(new javax.swing.ImageIcon(getClass().getResource("/Image Folder/hidden.png"))); // NOI18N
        showHideButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showHideButton1ActionPerformed(evt);
            }
        });

        UsernameTextField.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image Folder/user.png"))); // NOI18N
        UsernameTextField.setPlaceholderText("Username");

        PasswordTextField.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image Folder/padlock.png"))); // NOI18N
        PasswordTextField.setPlaceholderText("Password");

        javax.swing.GroupLayout LoginPanelLayout = new javax.swing.GroupLayout(LoginPanel);
        LoginPanel.setLayout(LoginPanelLayout);
        LoginPanelLayout.setHorizontalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(LoginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(LoginPanelLayout.createSequentialGroup()
                                .addComponent(SignupLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                                .addComponent(CloseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LoginButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SignupLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginPanelLayout.createSequentialGroup()
                                .addComponent(PasswordTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(showHideButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(UsernameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        LoginPanelLayout.setVerticalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(LoginLabel)
                .addGap(39, 39, 39)
                .addComponent(UsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showHideButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SignupLabel1)
                .addGap(53, 53, 53)
                .addComponent(LoginButton)
                .addGap(163, 163, 163)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SignupLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CloseButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(38, 38, 38))
        );

        LoginPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {PasswordTextField, showHideButton1});

        getContentPane().add(LoginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 58, -1, -1));

        FontaineBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image Folder/FontaineBG.jpeg"))); // NOI18N
        getContentPane().add(FontaineBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1280, -790, -1, -1));

        setSize(new java.awt.Dimension(968, 785));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_CloseButtonActionPerformed

    private void showHideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showHideButtonActionPerformed

    }//GEN-LAST:event_showHideButtonActionPerformed

    private void SignupLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignupLabelMouseClicked
        // TODO add your handling code here:
        SignUpDialog forgot = new SignUpDialog(); 
        this.dispose();
        forgot.setVisible(true);
    }//GEN-LAST:event_SignupLabelMouseClicked

    private void showHideButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showHideButton1ActionPerformed
        // TODO add your handling code here:
        if (showHideButton1.isPasswordVisible()) {
            // If it's visible, show the password text
            PasswordTextField.setEchoChar((char) 0);
        } else {
            // If it's not visible, hide the password text
            PasswordTextField.setEchoChar('*');
        }
    }//GEN-LAST:event_showHideButton1ActionPerformed

    private void SignupLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignupLabel1MouseClicked
        // TODO add your handling code here:
        ForgotPasswordDialog forgot = new ForgotPasswordDialog(); 
        this.dispose();
        forgot.setVisible(true);
    }//GEN-LAST:event_SignupLabel1MouseClicked

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
        try {
            Connection con = Connector.getConnection();

            String sql = "SELECT * FROM student WHERE `Username = ? AND Password = ?";
            PreparedStatement pst = con.prepareStatement(sql);

            pst.setString(2, UsernameTextField.getText());          // Username
            pst.setString(3, PasswordTextField.getText());          // Password

            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                // ✅ Login success
                MainForm forgot = new MainForm(); 
                 this.dispose();
                    forgot.setVisible(true);
                return;
            } else {
                // ❌ Login failed
                JOptionPane.showMessageDialog(null, "Invalid user. Try Again!");
                UsernameTextField.setText("");
                PasswordTextField.setText("");
                UsernameTextField.requestFocus();

            }

            rs.close();
            pst.close();
            con.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Database error: " + e.getMessage());

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "User ID must be a number!");

        }
    }//GEN-LAST:event_LoginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LoginDialog dialog = new LoginDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseButton;
    private javax.swing.JLabel FontaineBG;
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel LoginLabel;
    private javax.swing.JPanel LoginPanel;
    private Custom_Components.RoundPasswordField PasswordTextField;
    private javax.swing.JLabel SignupLabel;
    private javax.swing.JLabel SignupLabel1;
    private Custom_Components.RoundTextField UsernameTextField;
    private Custom_Components.ShowHideButton showHideButton1;
    // End of variables declaration//GEN-END:variables
}
