
import Custom_Components.RoundedPanel;
import Custom_Components.RoundedButton;
import Custom_Components.RoundPasswordField;
import Custom_Components.RoundTextField;
import Custom_Components.ImageButton;
import Custom_Components.ShowHideButton;
import Custom_Components.TextPrompt;
import DataBaseConnection.Connector;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author bello
 */
public class SignUpDialog extends javax.swing.JDialog {

    /**
     * Creates new form SignUpDialog
     */
    public SignUpDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setUndecorated(true);
        setBackground(new Color(0, 0, 0, 0));
        initComponents();
    }
    
    SignUpDialog() {
        this((java.awt.Frame) null, true);
        this.setUndecorated(true);
        setBackground(new Color(0, 0, 0, 0));
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginPanel = new RoundedPanel(35);
        LoginLabel = new javax.swing.JLabel();
        SignUpButton = new RoundedButton();
        BackButton = new ImageButton();
        CloseButton = new ImageButton();
        showHideButton1 = new ShowHideButton();
        showHideButton2 = new ShowHideButton();
        UsernameTextField = new Custom_Components.RoundTextField();
        PasswordTextField = new Custom_Components.RoundPasswordField();
        ConfirmPasswordTextField = new Custom_Components.RoundPasswordField();
        LastnameTextField = new Custom_Components.RoundTextField();
        FirstnameTextField = new Custom_Components.RoundTextField();
        MiddlenameTextField = new Custom_Components.RoundTextField();
        ProgramTextField = new Custom_Components.RoundTextField();
        YearTextField = new Custom_Components.RoundTextField();
        SectionTextField = new Custom_Components.RoundTextField();
        BarangayTextField = new Custom_Components.RoundTextField();
        jLabel1 = new javax.swing.JLabel();
        CityTextField = new Custom_Components.RoundTextField();
        ProvinceTextField = new Custom_Components.RoundTextField();
        CountryTextField = new Custom_Components.RoundTextField();
        jLabel2 = new javax.swing.JLabel();
        ContactNumberTextField = new Custom_Components.RoundTextField();
        jLabel3 = new javax.swing.JLabel();
        FontaineBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(962, 576));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginPanel.setBackground(new java.awt.Color(255, 255, 255));
        LoginPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        LoginLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        LoginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginLabel.setText("SIGN UP");
        LoginLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        SignUpButton.setBackground(new java.awt.Color(51, 153, 255));
        SignUpButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        SignUpButton.setForeground(new java.awt.Color(255, 255, 255));
        SignUpButton.setText("Sign Up");
        SignUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpButtonActionPerformed(evt);
            }
        });

        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image Folder/left-arrow.png"))); // NOI18N
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        CloseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image Folder/exit-full-screen.png"))); // NOI18N
        CloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseButtonActionPerformed(evt);
            }
        });

        showHideButton1.setText("showHideButton1");
        showHideButton1.setHideIcon(new javax.swing.ImageIcon(getClass().getResource("/Image Folder/eye.png"))); // NOI18N
        showHideButton1.setShowIcon(new javax.swing.ImageIcon(getClass().getResource("/Image Folder/hidden.png"))); // NOI18N
        showHideButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showHideButton1ActionPerformed(evt);
            }
        });

        showHideButton2.setText("showHideButton1");
        showHideButton2.setHideIcon(new javax.swing.ImageIcon(getClass().getResource("/Image Folder/eye.png"))); // NOI18N
        showHideButton2.setShowIcon(new javax.swing.ImageIcon(getClass().getResource("/Image Folder/hidden.png"))); // NOI18N
        showHideButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showHideButton2ActionPerformed(evt);
            }
        });

        UsernameTextField.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image Folder/user.png"))); // NOI18N
        UsernameTextField.setPlaceholderText("Username");
        UsernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameTextFieldActionPerformed(evt);
            }
        });

        PasswordTextField.setPlaceholderText("Password");
        PasswordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordTextFieldActionPerformed(evt);
            }
        });

        ConfirmPasswordTextField.setPlaceholderText("Confirm Password");

        LastnameTextField.setPlaceholderText("Last name");
        LastnameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastnameTextFieldActionPerformed(evt);
            }
        });

        FirstnameTextField.setPlaceholderText("First name");
        FirstnameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstnameTextFieldActionPerformed(evt);
            }
        });

        MiddlenameTextField.setPlaceholderText("Middle name");
        MiddlenameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiddlenameTextFieldActionPerformed(evt);
            }
        });

        ProgramTextField.setPlaceholderText("Program");
        ProgramTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProgramTextFieldActionPerformed(evt);
            }
        });

        YearTextField.setPlaceholderText("Year");
        YearTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YearTextFieldActionPerformed(evt);
            }
        });

        SectionTextField.setPlaceholderText("Section");
        SectionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SectionTextFieldActionPerformed(evt);
            }
        });

        BarangayTextField.setPlaceholderText("Barangay");
        BarangayTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarangayTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel1.setText("WHERE DO YOU LIVE");

        CityTextField.setPlaceholderText("City");
        CityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CityTextFieldActionPerformed(evt);
            }
        });

        ProvinceTextField.setPlaceholderText("Province");
        ProvinceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProvinceTextFieldActionPerformed(evt);
            }
        });

        CountryTextField.setPlaceholderText("Country");
        CountryTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CountryTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel2.setText("CONTACT");

        ContactNumberTextField.setPlaceholderText("Contact Number");
        ContactNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactNumberTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel3.setText("PERSONAL DETAILS");

        javax.swing.GroupLayout LoginPanelLayout = new javax.swing.GroupLayout(LoginPanel);
        LoginPanel.setLayout(LoginPanelLayout);
        LoginPanelLayout.setHorizontalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LoginPanelLayout.createSequentialGroup()
                                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, LoginPanelLayout.createSequentialGroup()
                                            .addComponent(BarangayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(CityTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(LoginPanelLayout.createSequentialGroup()
                                            .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(LoginPanelLayout.createSequentialGroup()
                                                    .addComponent(LastnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(FirstnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jLabel1)
                                                .addComponent(jLabel3))
                                            .addGap(16, 16, 16))
                                        .addComponent(CountryTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(LoginPanelLayout.createSequentialGroup()
                                        .addComponent(ProgramTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(YearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(LoginPanelLayout.createSequentialGroup()
                                        .addComponent(MiddlenameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(LoginPanelLayout.createSequentialGroup()
                                        .addComponent(ProvinceTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(8, 8, 8))
                                    .addGroup(LoginPanelLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(SectionTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(LoginPanelLayout.createSequentialGroup()
                                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(LoginPanelLayout.createSequentialGroup()
                                        .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 230, Short.MAX_VALUE)
                                        .addComponent(CloseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(SignUpButton, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                                    .addGroup(LoginPanelLayout.createSequentialGroup()
                                        .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(PasswordTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ConfirmPasswordTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(showHideButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(showHideButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(UsernameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2)
                                    .addComponent(ContactNumberTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(LoginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
        );

        LoginPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {showHideButton1, showHideButton2});

        LoginPanelLayout.setVerticalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(LoginLabel)
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LastnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FirstnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MiddlenameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProgramTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(YearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SectionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BarangayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProvinceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(CountryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ContactNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(UsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showHideButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showHideButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(SignUpButton)
                .addGap(29, 29, 29)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BackButton)
                    .addComponent(CloseButton))
                .addGap(49, 49, 49))
        );

        LoginPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {SignUpButton, showHideButton1, showHideButton2});

        getContentPane().add(LoginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 58, -1, 710));

        FontaineBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image Folder/FontaineBG.jpeg"))); // NOI18N
        getContentPane().add(FontaineBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2230, -410, -1, -1));

        setSize(new java.awt.Dimension(968, 785));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_CloseButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        LoginDialog forgot = new LoginDialog(); 
        this.dispose();
        forgot.setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void showHideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showHideButtonActionPerformed
        // TODO add your handling code here:  
    }//GEN-LAST:event_showHideButtonActionPerformed

    private void showHideButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showHideButton2ActionPerformed
        // TODO add your handling code here:
        if (showHideButton2.isPasswordVisible()) {
            // If it's visible, show the password text
            ConfirmPasswordTextField.setEchoChar((char) 0);
        } else {
            // If it's not visible, hide the password text
            ConfirmPasswordTextField.setEchoChar('*');
        }
    }//GEN-LAST:event_showHideButton2ActionPerformed

    private void showHideButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showHideButton1ActionPerformed
        // TODO add your handling code here:
         if (showHideButton1.isPasswordVisible()) {
            // If it's visible, show the password text
            PasswordTextField.setEchoChar((char) 0);
        } else {
            // If it's not visible, hide the password text
            PasswordTextField.setEchoChar('*');
        }
    }//GEN-LAST:event_showHideButton1ActionPerformed

    private void LastnameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastnameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastnameTextFieldActionPerformed

    private void UsernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameTextFieldActionPerformed

    private void FirstnameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstnameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstnameTextFieldActionPerformed

    private void MiddlenameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiddlenameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MiddlenameTextFieldActionPerformed

    private void ProgramTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProgramTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProgramTextFieldActionPerformed

    private void YearTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YearTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YearTextFieldActionPerformed

    private void SectionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SectionTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SectionTextFieldActionPerformed

    private void BarangayTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarangayTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BarangayTextFieldActionPerformed

    private void CityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CityTextFieldActionPerformed

    private void ProvinceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProvinceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProvinceTextFieldActionPerformed

    private void CountryTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CountryTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CountryTextFieldActionPerformed

    private void ContactNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactNumberTextFieldActionPerformed

    private void PasswordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordTextFieldActionPerformed

    private void SignUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpButtonActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
// Collect values
String Lastname   = LastnameTextField.getText();
String firstName  = FirstnameTextField.getText();
String middleName = MiddlenameTextField.getText();
String userName   = UsernameTextField.getText();
//String birthmonth = cbMonth.getSelectedItem().toString();
//String birthday   = cbDay.getSelectedItem().toString();
//String birthyear  = cbYear.getSelectedItem().toString();
String college      = ProgramTextField.getText();
String grade      = YearTextField.getText();
String Section      = SectionTextField.getText();
String brgy      = BarangayTextField.getText();
//String gender     = GenderChoice.getSelectedItem().toString();
//String strt       = Stree.getText();
String cty        = CityTextField.getText();
String prov       = ProvinceTextField.getText();
//String pstlcd     = PostalCode.getText();
String cntry      = CountryTextField.getText();
String contact = ContactNumberTextField.getText();
// Password fields
String password   = new String(PasswordTextField.getPassword());
String retype     = new String(ConfirmPasswordTextField.getPassword());

// --- VALIDATIONS ---
// Empty fields
// --- VALIDATIONS ---
// Empty fields
if (Lastname.isEmpty() || firstName.isEmpty() || middleName.isEmpty() || userName.isEmpty() ||
    password.isEmpty() || retype.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Please fill in all required fields.",
                                  "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

// Passwords match
if (!password.equals(retype)) {
    JOptionPane.showMessageDialog(this, "Passwords do not match!",
                                  "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

// ComboBox defaults
//if (birthmonth.equals("Month") || birthday.equals("Day") ||
  //  birthyear.equals("Year") || gender.equals("Select Gender")) {
    //JOptionPane.showMessageDialog(this, "Please complete your birthday and gender.",
    //                              "Error", JOptionPane.ERROR_MESSAGE);
    //return;
//}

// --- DATABASE INSERT ---
// Only one block
try (Connection con = Connector.getConnection()) {
    // 1️⃣ Check username BEFORE insert
    String checkSql = "SELECT COUNT(*) FROM student WHERE Username = ?";
    PreparedStatement checkPst = con.prepareStatement(checkSql);
    checkPst.setString(1, userName);
    ResultSet checkRs = checkPst.executeQuery();

    if (checkRs.next() && checkRs.getInt(1) > 0) {
        JOptionPane.showMessageDialog(this,
                "Username already exists. Please choose another one.",
                "Error", JOptionPane.ERROR_MESSAGE);
        return; // exit immediately
    }

    // 2️⃣ Insert new user
    String sql = "INSERT INTO student (`LastName`, `FirstName`, `MiddleName`, `Program`, `YearLevel`, `Section`, `Barangay`, `City`, `Province`,`Country`, `Contact_number`, `Username`, `Password`) "
               + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? )";

    PreparedStatement pst = con.prepareStatement(sql, java.sql.Statement.RETURN_GENERATED_KEYS);
    pst.setString(1, Lastname);
    pst.setString(2, firstName);
    pst.setString(3, middleName);
    pst.setString(4, college);
    pst.setString(5, grade);
    pst.setString(6, Section);
    //pst.setString(6, birthmonth);
    //pst.setString(7, birthday);
    //pst.setString(8, birthyear);
    //pst.setString(9, gender);
    pst.setString(7, brgy);
    //pst.setString(11, strt);
    pst.setString(8, cty);
    pst.setString(9, prov);
    //pst.setString(14, pstlcd);
    pst.setString(10, cntry);
    pst.setString(11, contact);
    pst.setString(12, userName);
    pst.setString(13, password);

    pst.executeUpdate();

    // 3️⃣ Get generated ID
    ResultSet rs = pst.getGeneratedKeys();
    int generatedId = -1;
    if (rs.next()) {
        generatedId = rs.getInt(1);
    }

    // 4️⃣ Success dialogs
    JOptionPane.showMessageDialog(this,
            "Registration successful!\nPlease make sure to remember your UID\nYour User ID is: " + generatedId,
            "Success", JOptionPane.INFORMATION_MESSAGE);

    this.dispose(); // close signup form
    MainForm main = new MainForm();
    main.setVisible(true);

} catch (SQLException sqlEx) {
    JOptionPane.showMessageDialog(this,
            "Database error: " + sqlEx.getMessage(),
            "SQL Error", JOptionPane.ERROR_MESSAGE);

} catch (HeadlessException e) {
    JOptionPane.showMessageDialog(this,
            "Unexpected error: " + e.getMessage(),
            "Error", JOptionPane.ERROR_MESSAGE);
}


    }//GEN-LAST:event_SignUpButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SignUpDialog dialog = new SignUpDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private Custom_Components.RoundTextField BarangayTextField;
    private Custom_Components.RoundTextField CityTextField;
    private javax.swing.JButton CloseButton;
    private Custom_Components.RoundPasswordField ConfirmPasswordTextField;
    private Custom_Components.RoundTextField ContactNumberTextField;
    private Custom_Components.RoundTextField CountryTextField;
    private Custom_Components.RoundTextField FirstnameTextField;
    private javax.swing.JLabel FontaineBG;
    private Custom_Components.RoundTextField LastnameTextField;
    private javax.swing.JLabel LoginLabel;
    private javax.swing.JPanel LoginPanel;
    private Custom_Components.RoundTextField MiddlenameTextField;
    private Custom_Components.RoundPasswordField PasswordTextField;
    private Custom_Components.RoundTextField ProgramTextField;
    private Custom_Components.RoundTextField ProvinceTextField;
    private Custom_Components.RoundTextField SectionTextField;
    private javax.swing.JButton SignUpButton;
    private Custom_Components.RoundTextField UsernameTextField;
    private Custom_Components.RoundTextField YearTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private Custom_Components.ShowHideButton showHideButton1;
    private Custom_Components.ShowHideButton showHideButton2;
    // End of variables declaration//GEN-END:variables
}
