
import Custom_Components.RoundedPanel;
import Custom_Components.RoundedButton;
import Custom_Components.RoundPasswordField;
import Custom_Components.RoundTextField;
import Custom_Components.ImageButton;
import Custom_Components.ProfilePanel;
import Custom_Components.ShowHideButton;
import Custom_Components.TextPrompt;
import Custom_Components.ThinScrollBarUI;
import Custom_Components.ThinScrollDemo;
import DataBaseConnection.Connector;
//import com.mysql.cj.xdevapi.Statement;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.JButton;                    // For the button
import javax.swing.JFileChooser;               // For file chooser dialog
import javax.swing.filechooser.FileNameExtensionFilter; // To filter image files
import javax.swing.JTextField;                 // Optional, for displaying file path
import javax.swing.JFrame;                     // Your form window
import javax.swing.JPanel;                     // Your panel layout
import java.awt.event.ActionListener;          // For button click listener
import java.awt.event.ActionEvent;             // For event object in listener
import java.io.File;                           // To handle the selected file
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author bello
 */
public class SignUpDialog extends javax.swing.JDialog {

    /**
     * Creates new form SignUpDialog
     */
    public SignUpDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
 
        this.setUndecorated(true);
        setBackground(new Color(0, 0, 0, 0));
        
        initComponents();
        
        ProfilePanel profilePicLabel = new ProfilePanel();
        profilePicLabel.setPreferredSize(new Dimension(100, 100)); // example size
        LoginPanel.add(profilePicLabel); // Add it to your panel

        ScrollPanel.setBorder(BorderFactory.createEmptyBorder());
        PanelHolder.setBorder(BorderFactory.createEmptyBorder());
        ScrollPanel.getVerticalScrollBar().setUI(new ThinScrollBarUI());
        ScrollPanel.getVerticalScrollBar().setPreferredSize(new Dimension(10, Integer.MAX_VALUE));
    }

    SignUpDialog() {
        this((java.awt.Frame) null, true);
        this.setUndecorated(true);
        setBackground(new Color(0, 0, 0, 0));

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelHolder = new javax.swing.JPanel();
        ScrollPanel = new javax.swing.JScrollPane();
        LoginPanel = new javax.swing.JPanel();
        LoginLabel = new javax.swing.JLabel();
        SignUpButton = new RoundedButton();
        BackButton = new ImageButton();
        CloseButton = new ImageButton();
        showHideButton1 = new ShowHideButton();
        showHideButton2 = new ShowHideButton();
        UsernameTextField = new Custom_Components.RoundTextField();
        PasswordTextField = new Custom_Components.RoundPasswordField();
        ConfirmPasswordTextField = new Custom_Components.RoundPasswordField();
        LastnameTextField = new Custom_Components.RoundTextField();
        FirstnameTextField = new Custom_Components.RoundTextField();
        MiddlenameTextField = new Custom_Components.RoundTextField();
        BarangayTextField = new Custom_Components.RoundTextField();
        jLabel1 = new javax.swing.JLabel();
        CityTextField = new Custom_Components.RoundTextField();
        ProvinceTextField = new Custom_Components.RoundTextField();
        CountryTextField = new Custom_Components.RoundTextField();
        jLabel2 = new javax.swing.JLabel();
        ContactNumberTextField = new Custom_Components.RoundTextField();
        jLabel3 = new javax.swing.JLabel();
        EmailTextField = new Custom_Components.RoundTextField();
        jLabel4 = new javax.swing.JLabel();
        PhotoUploader = new Custom_Components.RoundedButton();
        profilePathField = new Custom_Components.RoundTextField();
        profilePicLabel = new Custom_Components.ProfilePanel();
        FontaineBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(962, 576));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelHolder.setOpaque(false);

        ScrollPanel.setBackground(new java.awt.Color(255, 255, 255));
        ScrollPanel.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        ScrollPanel.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        ScrollPanel.setOpaque(false);

        LoginPanel.setBackground(new java.awt.Color(255, 255, 255));
        LoginPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        LoginLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        LoginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginLabel.setText("SIGN UP");
        LoginLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        SignUpButton.setBackground(new java.awt.Color(51, 153, 255));
        SignUpButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SignUpButton.setForeground(new java.awt.Color(255, 255, 255));
        SignUpButton.setText("Sign Up");
        SignUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpButtonActionPerformed(evt);
            }
        });

        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image Folder/left-arrow.png"))); // NOI18N
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        CloseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image Folder/exit-full-screen.png"))); // NOI18N
        CloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseButtonActionPerformed(evt);
            }
        });

        showHideButton1.setText("showHideButton1");
        showHideButton1.setHideIcon(new javax.swing.ImageIcon(getClass().getResource("/Image Folder/eye.png"))); // NOI18N
        showHideButton1.setShowIcon(new javax.swing.ImageIcon(getClass().getResource("/Image Folder/hidden.png"))); // NOI18N
        showHideButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showHideButton1ActionPerformed(evt);
            }
        });

        showHideButton2.setText("showHideButton1");
        showHideButton2.setHideIcon(new javax.swing.ImageIcon(getClass().getResource("/Image Folder/eye.png"))); // NOI18N
        showHideButton2.setShowIcon(new javax.swing.ImageIcon(getClass().getResource("/Image Folder/hidden.png"))); // NOI18N
        showHideButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showHideButton2ActionPerformed(evt);
            }
        });

        UsernameTextField.setPlaceholderText("Username");
        UsernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameTextFieldActionPerformed(evt);
            }
        });

        PasswordTextField.setPlaceholderText("Password");
        PasswordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordTextFieldActionPerformed(evt);
            }
        });

        ConfirmPasswordTextField.setPlaceholderText("Confirm Password");
        ConfirmPasswordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmPasswordTextFieldActionPerformed(evt);
            }
        });

        LastnameTextField.setPlaceholderText("Last name");
        LastnameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastnameTextFieldActionPerformed(evt);
            }
        });

        FirstnameTextField.setPlaceholderText("First name");
        FirstnameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstnameTextFieldActionPerformed(evt);
            }
        });

        MiddlenameTextField.setPlaceholderText("Middle name");
        MiddlenameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiddlenameTextFieldActionPerformed(evt);
            }
        });

        BarangayTextField.setPlaceholderText("Barangay");
        BarangayTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarangayTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel1.setText("WHERE DO YOU LIVE");

        CityTextField.setPlaceholderText("City");
        CityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CityTextFieldActionPerformed(evt);
            }
        });

        ProvinceTextField.setPlaceholderText("Province");
        ProvinceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProvinceTextFieldActionPerformed(evt);
            }
        });

        CountryTextField.setPlaceholderText("Country");
        CountryTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CountryTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel2.setText("CONTACT");

        ContactNumberTextField.setPlaceholderText("Contact Number");
        ContactNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactNumberTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel3.setText("PERSONAL DETAILS");

        EmailTextField.setPlaceholderText("Email");
        EmailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel4.setText("CREATE PROFILE PICTURE");

        PhotoUploader.setText("Upload Photo");
        PhotoUploader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhotoUploaderActionPerformed(evt);
            }
        });

        profilePathField.setMaximumSize(new java.awt.Dimension(64, 26));
        profilePathField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilePathFieldActionPerformed(evt);
            }
        });

        profilePicLabel.setForeground(new java.awt.Color(204, 204, 204));
        profilePicLabel.setText("Update Profile Picture");

        javax.swing.GroupLayout LoginPanelLayout = new javax.swing.GroupLayout(LoginPanel);
        LoginPanel.setLayout(LoginPanelLayout);
        LoginPanelLayout.setHorizontalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(PhotoUploader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(163, Short.MAX_VALUE))
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(profilePicLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, LoginPanelLayout.createSequentialGroup()
                                .addComponent(BarangayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CityTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(LoginPanelLayout.createSequentialGroup()
                                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(LoginPanelLayout.createSequentialGroup()
                                        .addComponent(LastnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(FirstnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(16, 16, 16))
                            .addComponent(CountryTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LoginPanelLayout.createSequentialGroup()
                                .addComponent(MiddlenameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 35, Short.MAX_VALUE))
                            .addGroup(LoginPanelLayout.createSequentialGroup()
                                .addComponent(ProvinceTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(43, 43, 43))))
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4)
                                .addGroup(LoginPanelLayout.createSequentialGroup()
                                    .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 230, Short.MAX_VALUE)
                                    .addComponent(CloseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(SignUpButton, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                                .addGroup(LoginPanelLayout.createSequentialGroup()
                                    .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(PasswordTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ConfirmPasswordTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(showHideButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(showHideButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(UsernameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addComponent(ContactNumberTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EmailTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(profilePathField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(LoginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        LoginPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {showHideButton1, showHideButton2});

        LoginPanelLayout.setVerticalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(LoginLabel)
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LastnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FirstnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MiddlenameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BarangayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProvinceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(CountryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ContactNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(UsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showHideButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showHideButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(profilePathField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PhotoUploader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(profilePicLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(SignUpButton)
                .addGap(29, 29, 29)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BackButton)
                    .addComponent(CloseButton))
                .addGap(49, 49, 49))
        );

        LoginPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {SignUpButton, showHideButton1, showHideButton2});

        ScrollPanel.setViewportView(LoginPanel);

        javax.swing.GroupLayout PanelHolderLayout = new javax.swing.GroupLayout(PanelHolder);
        PanelHolder.setLayout(PanelHolderLayout);
        PanelHolderLayout.setHorizontalGroup(
            PanelHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelHolderLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(ScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PanelHolderLayout.setVerticalGroup(
            PanelHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHolderLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(ScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        getContentPane().add(PanelHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 420, 780));

        FontaineBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image Folder/FontaineBG.jpeg"))); // NOI18N
        getContentPane().add(FontaineBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2230, -410, -1, -1));

        setSize(new java.awt.Dimension(968, 717));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_CloseButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        LoginDialog forgot = new LoginDialog();
        this.dispose();
        forgot.setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void showHideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showHideButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showHideButtonActionPerformed

    private void showHideButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showHideButton2ActionPerformed
        // TODO add your handling code here:
        if (showHideButton2.isPasswordVisible()) {
            // If it's visible, show the password text
            ConfirmPasswordTextField.setEchoChar((char) 0);
        } else {
            // If it's not visible, hide the password text
            ConfirmPasswordTextField.setEchoChar('*');
        }
    }//GEN-LAST:event_showHideButton2ActionPerformed

    private void showHideButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showHideButton1ActionPerformed
        // TODO add your handling code here:
         if (showHideButton1.isPasswordVisible()) {
            // If it's visible, show the password text
            PasswordTextField.setEchoChar((char) 0);
        } else {
            // If it's not visible, hide the password text
            PasswordTextField.setEchoChar('*');
        }
    }//GEN-LAST:event_showHideButton1ActionPerformed

    private void LastnameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastnameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastnameTextFieldActionPerformed

    private void UsernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameTextFieldActionPerformed

    private void FirstnameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstnameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstnameTextFieldActionPerformed

    private void MiddlenameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiddlenameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MiddlenameTextFieldActionPerformed

    private void ContactNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactNumberTextFieldActionPerformed

    private void PasswordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordTextFieldActionPerformed

    private void SignUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpButtonActionPerformed
try(Connection con = Connector.getConnection()){
    String Lastname = LastnameTextField.getText();
    String Firstname = FirstnameTextField.getText();
    String Middlename = MiddlenameTextField.getText();
    String Barangay = BarangayTextField.getText();
    String City = CityTextField.getText();
    String Province = ProvinceTextField.getText();
    String Country = CountryTextField.getText();
    String CPnumber = ContactNumberTextField.getText();
    String Email = EmailTextField.getText();
    String Username = UsernameTextField.getText();
    
    String Password = new String (PasswordTextField.getPassword());
    String ConfirmPassword = new String (ConfirmPasswordTextField.getPassword());
    
    if (Lastname.isEmpty()||Firstname.isEmpty() || Middlename.isEmpty()||Barangay.isEmpty()|| City.isEmpty()
            ||Province.isEmpty()||Country.isEmpty()||CPnumber.isEmpty()||Email.isEmpty()||Username.isEmpty()||
            Password.isEmpty()||ConfirmPassword.isEmpty()){
        JOptionPane.showMessageDialog(this, "Please make sure to fill out all requirements", "Error",JOptionPane.ERROR_MESSAGE);
        return;
    }
    if (!Password.equals(ConfirmPassword)){
        JOptionPane.showMessageDialog(this, "Passwords Do not Match", "Error", JOptionPane.ERROR_MESSAGE);
    return;
    }
    //checks whether a username alreasy exist or not
    String CheckSql = "SELECT COUNT(*) FROM admin WHERE Username = ?";
    PreparedStatement checkPst = con.prepareStatement(CheckSql);
    checkPst.setString(1,Username);
    ResultSet checkRs = checkPst.executeQuery();
if (checkRs.next() && checkRs.getInt(1)>0){
    JOptionPane.showMessageDialog(this, "Username already exist", "Error", JOptionPane.ERROR_MESSAGE);
return;
}    
 // 4️⃣ Save profile picture (if selected)
    String profilePicDestPath = null;
    if (selectedProfilePath != null) {
        try {
                File source = new File(selectedProfilePath);
            String destDir = "profile_pics/";
            new File(destDir).mkdirs(); // create folder if not exists
            profilePicDestPath = destDir + "student_" + Username + ".jpg";
            Files.copy(source.toPath(), new File(profilePicDestPath).toPath(),
                       StandardCopyOption.REPLACE_EXISTING);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error saving profile picture: " + ex.getMessage());
        }
    }
    
    String SQL = "INSERT INTO admin"
            +"(`Admin_LName`,`Admin_FName`,`Admin_MName`,`Barangay`,`City`,`Province`,`Country`,`Admin_Contact_Number`,`Admin_Email`"
            + ",`Username`,`Admin_Password`,`Admin_Profile_Picture`)"
            + "VALUES(?,?,?,?,?,?,?,?,?,?,?,?)";
    PreparedStatement pst = con.prepareStatement(SQL,Statement.RETURN_GENERATED_KEYS);
    pst.setString(1, Lastname);
    pst.setString(2, Firstname);
    pst.setString(3, Middlename);
    pst.setString(4, Barangay);
    pst.setString(5, City);
    pst.setString(6, Province);
    pst.setString(7, Country);
    pst.setString(8, CPnumber);
    pst.setString(9, Email);
    pst.setString(10, Username);
    pst.setString(11, Password);
    pst.setString(12, profilePicDestPath);
    
    pst.executeUpdate();
    
        // 6️⃣ Get generated student ID
    ResultSet rs = pst.getGeneratedKeys();
    int generatedId = -1;
    if (rs.next()) {
        generatedId = rs.getInt(1);
    }

    // 7️⃣ Success message
    JOptionPane.showMessageDialog(this,
        "Registration successful!\nUser ID is: " + generatedId,
        "Success", JOptionPane.INFORMATION_MESSAGE);

    // Close sign-up form and open main form
    this.dispose();
    MainForm main = new MainForm(Username);
    main.setVisible(true);
    
}catch (SQLException ex) {
    JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage(),
                                  "SQL Error", JOptionPane.ERROR_MESSAGE);
} catch (HeadlessException ex) {
    JOptionPane.showMessageDialog(this, "Unexpected error: " + ex.getMessage(),
                                  "Error", JOptionPane.ERROR_MESSAGE);
}
    
    
    
    
    }//GEN-LAST:event_SignUpButtonActionPerformed

    private void ProvinceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProvinceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProvinceTextFieldActionPerformed

    private void CountryTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CountryTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CountryTextFieldActionPerformed

    private void CityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CityTextFieldActionPerformed

    private void BarangayTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarangayTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BarangayTextFieldActionPerformed

    private void EmailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailTextFieldActionPerformed

    private void PhotoUploaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhotoUploaderActionPerformed
JFileChooser fileChooser = new JFileChooser();
fileChooser.setDialogTitle("Select Profile Picture");
fileChooser.setFileFilter(new FileNameExtensionFilter(
        "Image files", "jpg", "jpeg", "png", "gif"));

int result = fileChooser.showOpenDialog(null);
if (result == JFileChooser.APPROVE_OPTION) {
    File selectedFile = fileChooser.getSelectedFile();
    selectedProfilePath = selectedFile.getAbsolutePath(); // use the class-level variable
    profilePathField.setText(selectedProfilePath); // optional

    // Load and display the image
    ImageIcon icon = new ImageIcon(selectedProfilePath);
    Image img = icon.getImage().getScaledInstance(
            profilePicLabel.getWidth(),
            profilePicLabel.getHeight(),
            Image.SCALE_SMOOTH
    );
    profilePicLabel.setIcon(new ImageIcon(img));
}

    }//GEN-LAST:event_PhotoUploaderActionPerformed

    private void ConfirmPasswordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmPasswordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfirmPasswordTextFieldActionPerformed

    private void profilePathFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilePathFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profilePathFieldActionPerformed
private String selectedProfilePath; // stores the path of the profile picture

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
      java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpDialog().setVisible(true);

            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private Custom_Components.RoundTextField BarangayTextField;
    private Custom_Components.RoundTextField CityTextField;
    private javax.swing.JButton CloseButton;
    private Custom_Components.RoundPasswordField ConfirmPasswordTextField;
    private Custom_Components.RoundTextField ContactNumberTextField;
    private Custom_Components.RoundTextField CountryTextField;
    private Custom_Components.RoundTextField EmailTextField;
    private Custom_Components.RoundTextField FirstnameTextField;
    private javax.swing.JLabel FontaineBG;
    private Custom_Components.RoundTextField LastnameTextField;
    private javax.swing.JLabel LoginLabel;
    private javax.swing.JPanel LoginPanel;
    private Custom_Components.RoundTextField MiddlenameTextField;
    private javax.swing.JPanel PanelHolder;
    private Custom_Components.RoundPasswordField PasswordTextField;
    private Custom_Components.RoundedButton PhotoUploader;
    private Custom_Components.RoundTextField ProvinceTextField;
    private javax.swing.JScrollPane ScrollPanel;
    private javax.swing.JButton SignUpButton;
    private Custom_Components.RoundTextField UsernameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private Custom_Components.RoundTextField profilePathField;
    private Custom_Components.ProfilePanel profilePicLabel;
    private Custom_Components.ShowHideButton showHideButton1;
    private Custom_Components.ShowHideButton showHideButton2;
    // End of variables declaration//GEN-END:variables
}
